### ISSUE TITLE
Denodo - Links not showing when Interface View leverages view from another VDB

### ISSUE THREAD

**Issue by tylerinsd** [Informatica-EIC/Custom-Scanners#23]
Denodo - Links not showing when Interface View leverages view from another VDB. The is present when viewing the information natively from Denodo. Please see screen shots.
<img width="1427" alt="Screen Shot 2019-09-19 at 2 38 15 PM" src="https://user-images.githubusercontent.com/22576083/65283105-4f0e0780-daeb-11e9-87b8-d5eb8ea15a8f.png">
<img width="1431" alt="Screen Shot 2019-09-19 at 12 17 45 PM" src="https://user-images.githubusercontent.com/22576083/65283106-4f0e0780-daeb-11e9-9334-46730791bd63.png">

**Comment by darren-wrigley** [comment]
we can test with the most recent version - links across databases are working ok in my test cases, where the scanner is not having any issues/errors
