### ISSUE TITLE
Denodo - Not retrieving all metadata. Account used is admin and can see VDB's and views in Denodo UI.

### ISSUE THREAD

**Issue by tylerinsd** [Informatica-EIC/Custom-Scanners#24]
Denodo - Not retrieving all metadata. Account used is admin and can see VDB's and views in Denodo UI.

**Comment by darren-wrigley** [comment]
Note: we thing this is fixed in v0.9.8.2 which should be updated later today (after testing)

the issue was an error looking for the end of some vql views - it was looking for );\n - often there is no closing ) character
