### ISSUE TITLE
Need the ability to encrypt password in properties file

### ISSUE THREAD

**Issue by tylerinsd** [Informatica-EIC/Custom-Scanners#30]
Need the ability to encrypt password in properties file

**Comment by darren-wrigley** [comment]
Hi Chris - i will look into this.  
i think there are a few options to consider:-

1 - using environment variables (so not putting the pwd in the .properties file)
2 - encrypting, using a key that exists within the scanner & a utility function to create/write the encrypted password
3 - re-factor the scanner to use the new scanner SDK - so any passwords are stored within EDC like the other scanners
  
i think #3 is the best longer term solution - but i would also like to look at the other options, or a combination of 1 & 2 as a recommended standard for other custom scanners

**Comment by darren-wrigley** [comment]
password encryption is now supported.  
start the scanner passing password - see notes in [](https://github.com/Informatica-EIC/Custom-Scanners/tree/master/Denodo_Scanner#readme)
