### ISSUE TITLE
How to display fields in a dataset in a predefined order?

### ISSUE THREAD

**Issue by atulsaurav** [Informatica-EIC/Custom-Scanners#37]
Relational models have an attribute called `Position` which is probably used to display fields in order specified by position. On the contrary, fields in custom metadata model dataset usually show up in alphabetical order. For structured datasets, this portrays an incorrect picture of file layout in terms of field position.

How to enforce an order of fields in a dataset that is present in a custom model?

**Comment by darren-wrigley** [comment]
the denodo scanner will store the field position using the attribute com.infa.ldm.relational.Position - it does this for tables and views
