### ISSUE TITLE
NPE when creating custom lineage

### ISSUE THREAD

**Issue by greg-infa** [Informatica-EIC/Custom-Scanners#39]
NPE is thrown, when creating a custom lineagem when a base view is using JDBC data source to Virtual Data Port.

The reason is that JDBC Wrapper for Denodo VDP does not contain schema. 
Wrapper.java with a proposed fix is attached (createWrapper method is modified).

```
static Wrapper createWrapper(String wrapperVQL, String inDatabase) {
        Wrapper wr = new Wrapper();
        // wr.dataSourceObj = ds;
        // System.out.println("raw wrapper=" + wr);

        wr = wr.parse(wrapperVQL, inDatabase);
        // System.out.println("cooked wr=" + wr);
        // Added due to errors when it is JDBC wrapper to Denodo VDP:
        if (wr.schema == null) {
        	wr.schema = inDatabase;
        }
        // Added due to errors when it is JDBC wrapper to Denodo VDP.
        return wr;
    }
```

[Wrapper.zip](https://github.com/Informatica-EIC/Custom-Scanners/files/8341030/Wrapper.zip)

.

**Comment by darren-wrigley** [comment]
i realized that this issue was fixed a while ago, but a PR for the changes was never submitted from my forked repository.

**Comment by darren-wrigley** [comment]
see comments above
