### ISSUE TITLE
Axon and EDC mismatch due to Denodo scanner & JDBC connection

### ISSUE THREAD

**Issue by zfWazid** [Informatica-EIC/Custom-Scanners#46]
Hi @darren-wrigley

We have implemented the suggestions you kept for using Denodo as JDBC connectors and it is working as expected in EDC but when integrated with Axon some of the views are getting displaying.

Im attaching the screenshot where you can see 29 views in EDC but Axon only two views are visible

Please help us in fixing the issue

![DenodoJDBC](https://user-images.githubusercontent.com/109784053/180374399-70dcf4cd-5ece-453e-9e8a-2370a90bda78.PNG)
![DendodoAxon](https://user-images.githubusercontent.com/109784053/180374695-d4a825b4-3581-4b15-b474-0ddb2de3c9ff.PNG)

**Comment by darren-wrigley** [comment]
this issue is not related to the denodo scanner, since you are using JDBC  (and you will not get lineage from any denodo objects).  
another issue will be raised to change the processing of core.dataSetUuid during the scan to allow for axon integration

**Comment by darren-wrigley** [comment]
see previous comment, not related to the denodo scanner
