### ISSUE TITLE
Error during metadata extraction

### ISSUE THREAD

**Issue by jeffclover** [Informatica-EIC/Custom-Scanners#53]
This is for CDGC. Executed the scanDenodo.sh on 1 catalog. Everything appears okay from that. When trying to execute in IICS MCC, we get an error. 

error: com.informatica.ccgf.services.scanner.framework.exceptions.ScannerExecutionException: com.informatica.ccgf.utility.sal.rest.ApiException: /mfa/api/v1/agentdata/copy :: ""

Log file attached. 
[Denodo_Scanner_POC_Denodo Custom_sync_logs (1).csv](https://github.com/Informatica-EIC/Custom-Scanners/files/11837436/Denodo_Scanner_POC_Denodo.Custom_sync_logs.1.csv)

**Comment by darren-wrigley** [comment]
@jeffclover  When you initiate the scan from MCC - are you uploading the .zip file created by the scanner, or referencing the path to where the file is on the agent machine?    will look at importing both ways & see what the logs report

**Comment by darren-wrigley** [comment]
closing, not a scanner issue.  if problem happens during metadata import (from .zip file) then cdgc support team should be able to troubleshoot
